marco, Update:: 속성 추가, totalPage가 itemsPerPage보다 크게하도록 수정,currentPage는 1부터 줄 수 있도록 수정
sniperfactory-official/sfac-designkit-flutter pull request #101
Opened 2023-08-16 02:11 UTC by Shin-Seung-Ho

## 요약 및 목적
속성 패딩마진 이름변경과 배경색 추가, totalPage가 itemsPerPage보다 커야하도록 수정, currentPage는 1부터 줄 수 있도록 수정
## 변경사항에 대한 자세한 설명
속성 padding을 indexBoxPadding으로 수정했고 margin속성을 indexBoxMargin으로 추가하였습니다. totalPage가 itemsPerPage보다 작으면 오류가 뜨도록 하였습니다. currentPage도 1보다 작으면 오류가 뜨도록 하였습니다. 그리고 height를 다시 추가하였습니다. 
## 리뷰어들에게 전달할 내용
확인해주세요
<br/>
<br/>

```
특정 동작을 수행하는 다양한 키워드가 있지만
일단 'resolved' 혹은 'close'만 사용합니다.
ex) resolved: #issue_number (띄어쓰기 필수)
위의 예제처럼 입력할 시 merge를 할 경우 issue가 자동으로 close 됩니다
이 칸 아래에 적어주세요!
```
resolved: #53

2023-08-16 02:44 UTC, name27 commented
![image](https://github.com/sniperfactory-official/sfac-designkit-flutter/assets/50608974/bdfbe7ae-7b0a-47cb-ab92-992164e0efff)
중앙 정렬아 안돼요

2023-08-16 02:51 UTC, 2Juzzang commented
> ![image](https://user-images.githubusercontent.com/50608974/260886969-626cb0c0-4ae0-4ba6-b0de-155427ee230e.png) ![image](https://user-images.githubusercontent.com/50608974/260886941-1527c163-71c2-4a77-8f5f-ce283668f107.png)
> 
> 중앙 정렬아 안돼요

2023-08-16 08:45 UTC, 2Juzzang approved these changes
확인~

2023-08-18 02:57 UTC, name27 requested changes
currentPage required 말고 1로 기본값 주는건 어떄요?
보니까 currentPage 속성도 처음에만 값 받는 거라 initialPage가 더 나을거 같아여

2023-08-23 04:02 UTC, merged