judy, Feat:: NavigationMenu 위젯 추가 #62
sniperfactory-official/sfac-designkit-flutter pull request #63
Opened 2023-07-25 06:30 UTC by name27

## 요약 및 목적
NavigationMenu 위젯 추가
## 변경사항에 대한 자세한 설명
hover 시 배경 색과 텍스트 색이 달라지는 네비게이션 메뉴 위젯 추가 Function(int)? 형의 onTap 속성으로 index값을 받아 사용 가능
## 리뷰어들에게 전달할 내용
확인 부탁드립니다
<br/>
<br/>

```
특정 동작을 수행하는 다양한 키워드가 있지만
일단 'resolved' 혹은 'close'만 사용합니다.
ex) resolved: #issue_number (띄어쓰기 필수)
위의 예제처럼 입력할 시 merge를 할 경우 issue가 자동으로 close 됩니다
이 칸 아래에 적어주세요!
```
resolved: #62

2023-07-25 06:53 UTC, 2Juzzang requested changes

2023-07-25 06:53 UTC, 2Juzzang commented on lib/widgets/navigationMenu/navigation_menu.dart
> +    this.menuHeigh,
menuHeight 가 아닐까용~?
그리고 여기에 어떤 값을 넣어도 메뉴 세로크기는 변함이 없습니다!
height 값에 따라서만 변하네요

menuWidth를 줄 경우 텍스트가 왼쪽 정렬됩니다
가운데 정렬이 되도록 하거나 옵션을 줘야할 것 같습니다

2023-07-25 07:16 UTC, 2Juzzang approved these changes
잘 되네요 좋습니다~

2023-07-25 08:28 UTC, 2Juzzang approved these changes

2023-07-26 02:57 UTC, Shin-Seung-Ho requested changes

2023-07-26 02:57 UTC, Shin-Seung-Ho commented on lib/widgets/navigationMenu/navigation_menu.dart
> +    return SizedBox(
SFNavigationMenu 위젯 전체에 Expanded를 주고 width를 없애는건 어떨까요?

2023-07-26 04:42 UTC, name27 commented on lib/widgets/navigationMenu/navigation_menu.dart
> +    return SizedBox(
height 값은 ListVIew.builder때문에 필요해요

2023-07-28 06:36 UTC, closed without merging