judy, Feat:: 콤보박스, 셀렉, 셀렉 메인, 셀렉 서브 위젯 추가 #65
sniperfactory-official/sfac-designkit-flutter pull request #71
Opened 2023-07-27 07:34 UTC by name27

## 요약 및 목적
**ComboBox, Select, SelectMain, SelectSub 위젯 추가**
**SelectSub**
- `List<String>`으로 메뉴를 받으며 선택 및 hover 시 글자 색 변경
**SelectMain**
- con과 text를 받으며 하나의 메뉴
**Select**
- `onTap(p0){}` p0로 SelectMain 인덱스를 받는다
- SelectSub는 SelectSub 위젯을 사용할 때의 `onTap(p0){}` p0로 SelectMain 인덱스를 받는다
- SelectMain과 SelectSub를 사용하여 SelectSub를 사용할 시 SelectSub와 SelectMain의 길이가 같아야 한다.
- SelectMain의 서브 메뉴 없을 시 해당 인덱스와 동일한 SelectSub 리스트 인덱스에 null
**ComboBox**
- SelectMain 리스트를 오버레이로 드롭박스를 띄운다.
- `onTap(p0){}` p0로 SelectMain 인덱스를 받는다
- SFComboBoxnStatus.select : 드롭박스 리스트 선택
- SFComboBoxnStatus.searchSelect: SelectMain 리스트 검색, 선택 가능
- SFComboBoxnStatus.multiSelect: 추후 추가 예정

## 변경사항에 대한 자세한 설명

## 리뷰어들에게 전달할 내용
onSubmitted 주석한 상태랑 주석해제한 상태 둘 다 테스트 부탁드려요
텍스트필드 엔터 시 blue error 뜨는 현상 이슈 참고 부탁드려요

특정 동작을 수행하는 다양한 키워드가 있지만
일단 'resolved' 혹은 'close'만 사용합니다.
ex) resolved: #issue_number (띄어쓰기 필수)
위의 예제처럼 입력할 시 merge를 할 경우 issue가 자동으로 close 됩니다
이 칸 아래에 적어주세요!
```
resolved: #65

2023-07-27 08:56 UTC, 2Juzzang requested changes
콤보박스 카멜 케이스 > 스네이크 케이스로 변경하기

2023-07-28 04:53 UTC, 2Juzzang approved these changes
흠..

2023-07-28 07:33 UTC, 2Juzzang requested changes
마르코님이 문제점을 찾아내셔서 보류하겠습니다

2023-07-28 08:59 UTC, Shin-Seung-Ho requested changes
1. 콤보박스가 처음에는 선택된 항목이 없는데 드롭다운을 내리면 첫 번째 SFSelectMain 요소가 선택되어 있습니다.
2. 페이지 뒤로가기를 눌렀을 때 콤보박스 드롭다운이 남아있습니다.
3. SFSelectMain의 텍스트의 길이가 콤보박스의 width보다 길어지면 overflow 발생합니다. 텍스트오버플로우를 설정하는게 좋을 것 같습니다
4. SFSelectMain의 crossAxisAlignment: CrossAxisAlignment.start를 CrossAxisAlignment.center로 바꾸면 좋을것 같습니다. 아이콘이 커지면 text 위치가 이상하네요.
5. SFSelectMain의 icon속성을 leading으로 바꿔주시면 좋을것 같습니다. icon속성에 Icon이 아닌 위젯이 들어가도 오류가 나지않아서 직관성이 떨어지는거 같습니다.
6. SFSelectMain에 selectSub 속성이 사용되고 있지 않습니다.
7. enum SFComboBoxnStatus 에서 Box 뒤에 n은 오타인가요?
8. SFComboBox 위젯에 trailingIcon속성이름을 suffixIcon으로 바꾸는게 좋을 것 같습니다.
9. SFComboBox 위젯에 boxScorllPhysics속성 이름 오타있습니다.
10. width 속성들의 주석이 다 가로 넓이라고 되어있는데 가로 너비로 수정해주세요.
11. SFSelectGroup위젯과 SFSelectSub위젯에 initialndex속성 이름 I가 빠진거 같습니다.

2023-07-31 01:57 UTC, name27 commented
> 1. 콤보박스가 처음에는 선택된 항목이 없는데 드롭다운을 내리면 첫 번째 SFSelectMain 요소가 선택되어 있습니다.
수정했습니다
> 2. 페이지 뒤로가기를 눌렀을 때 콤보박스 드롭다운이 남아있습니다.
수정했습니다
> 3. SFSelectMain의 텍스트의 길이가 콤보박스의 width보다 길어지면 overflow 발생합니다. 텍스트오버플로우를 설정하는게 좋을 것 같습니다
textStyle로 사용자가 설정할 수 있어서 따로 overflow 처리 안 해도 될 거 같습니다
> 4. SFSelectMain의 crossAxisAlignment: CrossAxisAlignment.start를 CrossAxisAlignment.center로 바꾸면 좋을것 같습니다. 아이콘이 커지면 text 위치가 이상하네요.
수정했습니다
> 5. SFSelectMain의 icon속성을 leading으로 바꿔주시면 좋을것 같습니다. icon속성에 Icon이 아닌 위젯이 들어가도 오류가 나지않아서 직관성이 떨어지는거 같습니다.
Icon 타입으로 수정했습니다
> 6. SFSelectMain에 selectSub 속성이 사용되고 있지 않습니다.
SFSelectMain -> SFSelectMenu
SFSelectGroup -> SFSelectMain 으로 이름 변경했습니다.
기존 SFSelectMain은 icon이랑 text만 받는 위젯이며, SelectMain 형태의 위젯이 아니기 때문에 이름을 변경하였습니다
> 7. enum SFComboBoxnStatus 에서 Box 뒤에 n은 오타인가요?
네 ㅎ 수정했습니다
> 8. SFComboBox 위젯에 trailingIcon속성이름을 suffixIcon으로 바꾸는게 좋을 것 같습니다.
수정했습니다
> 9. SFComboBox 위젯에 boxScorllPhysics속성 이름 오타있습니다.
수정했습니다
> 10. width 속성들의 주석이 다 가로 넓이라고 되어있는데 가로 너비로 수정해주세요.
수정했습니다
> 11. SFSelectGroup위젯과 SFSelectSub위젯에 initialndex속성 이름 I가 빠진거 같습니다.
수정했습니다

2023-08-01 02:16 UTC, Shin-Seung-Ho requested changes
1. SFSelectMenu에서 icon속성은 나중에 저희가 추가할 아이콘이나 체크박스를 넣을 수도 있어서 위젯이 들어와야 할거같습니다.
leadingSpacing이라는 속성도 있으니 leading이 조금 더 나을 듯 싶습니다.

2. 피그마를 보니 SFSelectSub에서 menu속성 앞에도 leading속성이 필요할거같습니다.

3. SFComboBox에서 SFComboBoxStatus.searchSelect일 때 검색하고 SFSelectMenu를 클릭하면 다른 값이 포커스됩니다.

4. overflow가 안되네요

2023-08-01 06:27 UTC, name27 commented
> 1. SFSelectMenu에서 icon속성은 나중에 저희가 추가할 아이콘이나 체크박스를 넣을 수도 있어서 위젯이 들어와야 할거같습니다.
>    leadingSpacing이라는 속성도 있으니 leading이 조금 더 나을 듯 싶습니다.
_위젯으로 바꾸고 icon 에서 leading으로 바꿨습니다_
> 2. 피그마를 보니 SFSelectSub에서 menu속성 앞에도 leading속성이 필요할거같습니다.
_v1 에서는 없어서 지금은 추가 안 하겠습니다_
> 3. SFComboBox에서 SFComboBoxStatus.searchSelect일 때 검색하고 SFSelectMenu를 클릭하면 다른 값이 포커스됩니다.
_수정했습니다_
> 4. overflow가 안되네요
_됩니다_

2023-08-04 01:26 UTC, 2Juzzang requested changes

2023-08-04 01:26 UTC, 2Juzzang commented on lib/widgets/comboBox/select_sub.dart
> +    //this.height,
이거랑 밑에 주석처리 한 부분도 지워주세요~

2023-08-04 01:26 UTC, 2Juzzang commented on lib/widgets/comboBox/select_sub.dart
>        child: ListView.separated(
아래 여백이 위에보다 조금 더 있네요
ListView를 Center로 감싸주니 해결됩니다 수정 부탁드려요

2023-08-04 01:26 UTC, 2Juzzang commented on lib/widgets/comboBox/select_sub.dart
>        child: ListView.separated(
추가로 Center로 감싼 뒤에 menu 수가 늘어나면 위아래 여백이 점점 더 크게 생깁니다
이건 (widget.menus.length - 1) * widget.spacing 이 부분에서 (widget.spacing / 2) 하면 되네요

2023-08-04 01:26 UTC, 2Juzzang commented on lib/widgets/comboBox/combo_box.dart
> +    required this.menus,
메뉴가 빈 배열일 경우 콤보박스 누르면 에러나네요!

2023-08-04 01:35 UTC, name27 commented on lib/widgets/comboBox/combo_box.dart
> +    required this.menus,
위에서 고쳤슴다!

2023-08-04 01:38 UTC, 2Juzzang commented on lib/widgets/comboBox/select_sub.dart
>        child: ListView.separated(
main.. main입니다.. 죄송

2023-08-04 02:18 UTC, 2Juzzang commented
확인했습니다

2023-08-04 02:18 UTC, 2Juzzang approved these changes

2023-08-04 09:03 UTC, Shin-Seung-Ho approved these changes
진짜 고생많으셨습니다..

2023-08-04 09:03 UTC, merged