juno, Feat:: Toast 위젯 추가 #76
sniperfactory-official/sfac-designkit-flutter pull request #77
Opened 2023-08-02 01:46 UTC by 2Juzzang

## 요약 및 목적
Toast 위젯 추가

## 변경사항에 대한 자세한 설명
toast 상태별 (withAction, withTitle, simple, error, success) 기능 및 색상 추가
Opacity를 사용한 fadeout 애니메이션 추가

## 리뷰어들에게 전달할 내용
피그마에 작성된 폰트 크기나 색을 사용했는데 시뮬레이터에선 조금 작게 보입니다
추가할 부분이나 수정할 부분 알려주시면 반영하겠습니다
<br/>
<br/>

resolved: #76

2023-08-02 06:55 UTC, Shin-Seung-Ho requested changes
버튼에 대한 옵션은 안줘도 되나요?

2023-08-02 07:01 UTC, 2Juzzang commented on lib/widgets/toast/toast.dart
> +                    ? GestureDetector(
드..드리겠습니다..

2023-08-03 02:52 UTC, name27 requested changes
Matreial 안에 color: Colors.transparent 넣어줘야 토스트가 boder radius에 맞게 나와요
토스트 배경색도 속성에 추가하고 싶어요!

2023-08-03 04:24 UTC, Shin-Seung-Ho requested changes
1. titleTextStyle 적용안됩니다. 
2.color: Color(0xff99BDFF)가 SFColor.primary40이고 Color(0xffF5F8FF)가 SFColor.primary5인 것 같습니다.

2023-08-03 04:57 UTC, name27 approved these changes
확인했슴다

2023-08-03 04:59 UTC, Shin-Seung-Ho approved these changes
고생하셨습니다.

2023-08-03 05:56 UTC, merged