judy, Feat:: alert 위젯 추가 #94
sniperfactory-official/sfac-designkit-flutter pull request #95
Opened 2023-08-09 01:07 UTC by name27

## 요약 및 목적
closeWidget을 누르면 사라지는 alert 위젯
## 변경사항에 대한 자세한 설명

## 리뷰어들에게 전달할 내용
확인 부탁드려요
사용 방법
```
alert(
            context
            title: '로그인 실패',
            content: '틀린 회원정보입니다. 다시 로그인해주세요',
          );
```
<br/>
<br/>

```
특정 동작을 수행하는 다양한 키워드가 있지만
일단 'resolved' 혹은 'close'만 사용합니다.
ex) resolved: #issue_number (띄어쓰기 필수)
위의 예제처럼 입력할 시 merge를 할 경우 issue가 자동으로 close 됩니다
이 칸 아래에 적어주세요!
```
resolved: #94

2023-08-09 07:29 UTC, 2Juzzang requested changes

2023-08-09 07:29 UTC, 2Juzzang commented on lib/widgets/alert/alert.dart
> +  final Widget? closeWidget;
closeWidget을 직접 줄 경우 onTap이 빠져있어서 alert 창이 안닫힙니다~

2023-08-16 01:38 UTC, 2Juzzang approved these changes
수정확인했습니다

2023-08-16 02:45 UTC, Shin-Seung-Ho approved these changes
확인했습니다!

2023-08-16 02:47 UTC, merged