Date picker
sniperfactory-official/sfac-designkit-flutter pull request #96
Opened 2023-08-09 02:19 UTC by name27

## 요약 및 목적
**Calendar**
달력 기능
**DatePicker**
달력 기능 + 드롭 박스

`SFCalendarStatus.list`:  선택한 날짜 리스트
`SFCalendarStatus.range`: 선택한 기간
`SFCalendarStatus.one`: 선택한 날짜

`getSelectedDate` 속성를 통해 선택한 list, range(start, end), one 값을 받을 수 있다.
`getSelectedDate: (start, end, selectedDateList, selectedOne) {}`

## 변경사항에 대한 자세한 설명

## 리뷰어들에게 전달할 내용
확인 부탁드려요

<br/>
<br/>

```
특정 동작을 수행하는 다양한 키워드가 있지만
일단 'resolved' 혹은 'close'만 사용합니다.
ex) resolved: #issue_number (띄어쓰기 필수)
위의 예제처럼 입력할 시 merge를 할 경우 issue가 자동으로 close 됩니다
이 칸 아래에 적어주세요!
```

2023-08-09 07:50 UTC, 2Juzzang reviewed
final List<DateTime>? initialDateList;
final DateTimeRange? initialDateRange;
final DateTime? initialDateOne;

2023-08-09 07:50 UTC, 2Juzzang commented on lib/widgets/datepicker/date_picker.dart
>    final double? calendarHeight;
배경 박스만 줄어들고 날짜는 둥둥 떠다닙니다~

2023-08-09 07:50 UTC, 2Juzzang commented on lib/widgets/datepicker/date_picker.dart
>    final SFCalendarStatus status;
status -> type 으로 바꿔주세요~

2023-08-09 07:50 UTC, 2Juzzang commented on lib/widgets/datepicker/calendar.dart
>    final SFCalendarStatus status;
여기도 타입!

2023-08-09 07:50 UTC, 2Juzzang commented on lib/widgets/datepicker/date_picker.dart
>    final SFCalendarStatus status;
그리고 기본값은 range보다는 one이 좋을 것 같습니다

2023-08-09 07:56 UTC, 2Juzzang requested changes

2023-08-09 07:56 UTC, 2Juzzang commented on lib/widgets/datepicker/calendar.dart
> +  final bool todayMark;
false를 줘도 변하는게 없습니다!

2023-08-09 08:36 UTC, name27 commented on lib/widgets/datepicker/date_picker.dart
>    final SFCalendarStatus status;
수정했습니다

2023-08-09 08:36 UTC, name27 commented on lib/widgets/datepicker/calendar.dart
> +  final bool todayMark;
수정했습니다

2023-08-09 08:43 UTC, name27 commented
> final List? initialDateList; final DateTimeRange? initialDateRange; final DateTime? initialDateOne; 이 부분 예제코드좀 부탁드림다

```
SFDatePicker(
                initialDateList: [
                  DateTime.now(),
                  DateTime.now().add(Duration(days: 3))
                ],
                initialDateOne: DateTime.now(),
                initialDateRange: DateTimeRange(
                    start: DateTime.now(),
                    end: DateTime.now().add(Duration(days: 7))),
              ),
```

2023-08-10 01:00 UTC, 2Juzzang requested changes

2023-08-10 01:00 UTC, 2Juzzang commented on lib/widgets/datepicker/calendar.dart
> +  final SFCalendarStatus type;
저번에 말씀드렸던건데 this.type = SFCalendarStatus.one,
status 들어간 부분들을 type으로 바꿔달라는 말이었습니다 🥲

2023-08-10 01:01 UTC, 2Juzzang commented on lib/widgets/datepicker/calendar.dart
> +  final SFCalendarStatus type;
추가로 예제코드는
```
SFDatePicker(
    type: SFCalendarStatus.list,
    initialDateList: [
      DateTime(2023, 8, 2),
      DateTime(2023, 8, 10),
    ],
    initialDateOne: DateTime(2023, 8, 2),
    initialDateRange: DateTimeRange(
      start: DateTime(2023, 8, 1),
      end: DateTime(2023, 8, 31),
    ),
  ),
```
이런 식으로 날짜를 입력해주는게 맞겠네요

2023-08-10 01:29 UTC, name27 commented on lib/widgets/datepicker/calendar.dart
> +  final SFCalendarStatus type;
수정했습니다!

2023-08-10 02:39 UTC, 2Juzzang approved these changes
확인완료~

2023-08-10 06:35 UTC, Shin-Seung-Ho requested changes
1. SFDatePicker에서 selectTextStyle옵션 사용 우이합니꺼?
2. range타입을 쓰고 dark테마를 쓸경우 마지막선택한날이 살짝이상해보입니다.
![image](https://github.com/sniperfactory-official/sfac-designkit-flutter/assets/101088105/64c2fc13-24c3-4a0e-bbc8-dda0daa10ab9)
3. text는 드롭박스 text인데 textColor는 캘린더텍스트컬러라 조금 헷갈릴수있을거같습니다 캘린더텍스트컬러같은거로 헷갈리지 않게 해주시면 감사하겠슴다!

2023-08-16 02:37 UTC, 2Juzzang approved these changes
수정 확인

2023-08-16 09:38 UTC, Shin-Seung-Ho reviewed
수정된거 확인했습니다~
2번같은경우는 화면을 작게했을경우 보이네여...

2023-08-17 04:28 UTC, Shin-Seung-Ho approved these changes
확인했습니다!!!!!!

2023-08-17 04:29 UTC, merged