marco, Feat:: Toggle위젯 생성 #58
sniperfactory-official/sfac-designkit-flutter pull request #98
Opened 2023-08-09 08:27 UTC by Shin-Seung-Ho

## 요약 및 목적
Toggle 위젯 생성
## 변경사항에 대한 자세한 설명
Toggle위젯 만들었습니다 저번에 PR했던거에서 주디님이 말하신 value에 false로 초기값을 주고 initialValue로 속성명을 변경했습니다.
## 리뷰어들에게 전달할 내용
피드백 환영..
<br/>
<br/>

```
특정 동작을 수행하는 다양한 키워드가 있지만
일단 'resolved' 혹은 'close'만 사용합니다.
ex) resolved: #issue_number (띄어쓰기 필수)
위의 예제처럼 입력할 시 merge를 할 경우 issue가 자동으로 close 됩니다
이 칸 아래에 적어주세요!
```
resolved: #58

2023-08-10 06:15 UTC, 2Juzzang requested changes
animationDuration 속성 추가해서 커스텀 가능하게 하면 좋을 것 같습니다~

2023-08-10 06:15 UTC, 2Juzzang commented on lib/widgets/toggle/toggle.dart
> +              duration: const Duration(milliseconds: 200),
시간 커스텀할 수 있게 주면 좋겠네요!

2023-08-16 02:24 UTC, 2Juzzang approved these changes
수정 확인~

2023-08-16 02:26 UTC, name27 approved these changes
확인했습니다

2023-08-16 02:45 UTC, merged